language: php
php:
  - 7.1

before_script:
  - phpenv config-rm xdebug.ini
  - cp .env.example .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan passport:keys
  - php artisan migrate
  - npm install
  - npm run dev

before_install:
  - mysql -e 'CREATE DATABASE tiler;'
  - mysql -e 'CREATE DATABASE tiler_test;'

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

env:
  - TRAVIS_NODE_VERSION="4"